baseUrl = 'https://jkordick.github.io/'
title = 'I (try to) never think about losing'
summaryLength = 35
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[menu]
[[menu.nav]]
name = ":cool: blog"
URL = "#blog"
identifier = "blog"
weight = 1
[menu.nav.params]
class = "show active"

#[[menu.nav]]
#name = ":memo: portfolio"
#URL = "#portfolio"
#identifier = "portfolio"
#weight = 2
#[menu.nav.params]
#class = ""
#
[[menu.nav]]
name = ":rainbow: about"
URL = "#about"
identifier = "about"
weight = 3
[menu.nav.params]
class = ""

#[[menu.nav]]
#name = ":abc: imprint"
#URL = "#imprint"
#identifier = "imprint"
#weight = 4
#[menu.nav.params]
#class = ""

[params]

title = "Hello, my name is Julia!"
author = "Julia Kordick"
#copyright = "2020-2021"
description = "I am a"
pageDescription = 'Julia is writing about Software Architecture, DevOps and Diversity'
aboutDescription = "I am Cloud Solution Architect @ Microsoft"
socialsDescription = "Feel free to contact me:"
profilePicture = "images/profile.jpg"
favicon = "favicons/"

[[params.socialIcons]]
icon = "fab fa-linkedin-in fa-3x"
title = "Linkedin"
url = "https://www.linkedin.com/in/julia-kordick/"

[[params.socialIcons]]
icon = "fab fa-github fa-3x"
title = "GitHub"
url = "https://github.com/jkordick"

[[params.socialIcons]]
icon = "fas fa-envelope fa-3x"
title = "e-mail"
url = "mailto:moin@jkordick.dev"


