baseUrl = 'https://jkordick.github.io/'
title = 'I (try to) never think about losing'
summaryLength = 35
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

[menu]
    [[menu.nav]]
    name = ":cool: blog"
    URL = "/"
    weight = 1

    [[menu.nav]]
    name = ":memo: portfolio"
    URL = "#portfolio"
    weight = 2

    [[menu.nav]]
    name = ":rainbow: links"
    URL = "#links"
    weight = 3

    [[menu.nav]]
    name = ":abc: imprint"
    URL = "#imprint"
    weight = 4

[params]

title = "Hello, my name is Julia!"
author = "Julia Kordick"
#copyright = "2020-2021"
description = "I am a"
profilePicture = "images/profile.jpg"
favicon = "favicons/"
doNotLoadAnimations = false
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"


[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"




